name: Main Deployment Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Deploy in EC2 with SSH
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          command: |
            cd ~/wordpress
            git stash
            git checkout master
            git pull origin master
            
            composer install
            composer dumpautoload